services:
    mysql:
        image: mysql:8.3
        container_name: mysql-spring

        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: testdb
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
